# -*- coding: utf-8 -*-
"""Python_Project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qkdcp-5UZi29KlEav8hJvArtKL1a-53U

---


**Combating Social Media Addiction With Data-Driven Insights**

---
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Students Social Media Addiction (1).csv")

"""**Data Understanding & Cleaning**"""

print(df.head(5))   # Show first 5 rows
print(df.info())   #  Checking Column types & null
print(df.describe()) # Show Statistical summary

print(df.isnull().sum()) # yes it show no null values in dataset

# Fill missing values if any
df = df.fillna(df.mean(numeric_only=True))

# Check data types
print("\nData types:")
print(df.dtypes)

# Check for duplicates
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")
if duplicates > 0:
    df = df.drop_duplicates()
    print("Duplicates removed")

"""**Exploratory Data Analysis (EDA)**"""

#Understand distribution
print(df['Gender'].value_counts())
print(df['Age'].describe())

"""**Understand Relationships Between:**"""

# Age vs Daily Usage
df.groupby('Age')['Avg_Daily_Usage_Hours'].mean()

# Gender Vs Daily Usage
df.groupby('Gender')['Avg_Daily_Usage_Hours'].mean()

# Sleep vs Usage (correlation check)
df[['Avg_Daily_Usage_Hours','Sleep_Hours_Per_Night']].corr()

# Academic Level Vs Daily Usage
df.groupby('Academic_Level')['Avg_Daily_Usage_Hours'].mean()

# Country Vs Daily Usage
df.groupby('Country')['Avg_Daily_Usage_Hours'].mean()

# Correlation between Addicted Score to ( Daily Usage Hours, Conflicted Over Social Media, Sleep Hours And Mental Health)
correlation_usage_addiction = df['Addicted_Score'].corr(df['Avg_Daily_Usage_Hours'])
display(f"Correlation between Addicted_Score and Avg_Daily_Usage_Hours: {correlation_usage_addiction}")

correlation_conflicts_addiction = df['Addicted_Score'].corr(df['Conflicts_Over_Social_Media'])
display(f"Correlation between Addicted_Score and Conflicts_Over_Social_Media: {correlation_conflicts_addiction}")

correlation_sleep_addiction = df['Addicted_Score'].corr(df['Sleep_Hours_Per_Night'])
display(f"Correlation between Addicted_Score and Sleep_Hours_Per_Night: {correlation_sleep_addiction}")

correlation_mental_health_addiction = df['Addicted_Score'].corr(df['Mental_Health_Score'])
display(f"Correlation between Addicted_Score and Mental_Health_Score: {correlation_mental_health_addiction}")

"""**Aggregation And Insights**"""

# Groupby Genders
print(df.groupby("Gender")['Avg_Daily_Usage_Hours'].mean())

# Groupby Age Groups
df['Age_Group'] = pd.cut(df['Age'], bins=[10,15,20,25], labels=["11-15","16-20","21-25"])
print(df.groupby("Age_Group")['Avg_Daily_Usage_Hours'].mean())

# Groupby Educational Level
print(df.groupby("Academic_Level")['Avg_Daily_Usage_Hours'].mean())

"""**Functions, Loops, and Conditionals**"""

# Create Risk Level Classification Function based on usage hours
def classify_risk_level(usage_hours):
    """
    Classify students into addiction risk categories
    Low Risk: Less than 3 hours daily
    Medium Risk: 3-5 hours daily
    High Risk: More than 5 hours daily
    """
    if usage_hours < 3:
        return 'Low'
    elif usage_hours <= 5:
        return 'Medium'
    else:
        return 'High'

df['Risk_Level'] = df['Avg_Daily_Usage_Hours'].apply(classify_risk_level)

# Suggest digital detox strategies using if-else blocks
def suggest_strategy(risk):
    if risk == "Low":
        return "Maintain balance"
    elif risk == "Medium":
        return "Digital detox weekends"
    else:
        return "Seek counseling & reduce gradually"


df['Strategy'] = df['Risk_Level'].apply(suggest_strategy)

# Sleep Quality Category
def sleep_quality(hours):
    if hours >= 8:
        return "Good"
    elif hours >= 6:
        return "Average"
    else:
        return "Poor"

df['Sleep_Quality'] = df['Sleep_Hours_Per_Night'].apply(sleep_quality)

"""**Data Visualization**"""

# Bar Chart → Daily Usage by Age Group
df.groupby("Age_Group")['Avg_Daily_Usage_Hours'].mean().plot(kind='bar')
ax = sns.countplot(x='Age_Group', data=df)
ax.bar_label(ax.containers[0])
plt.title("Average Daily Usage by Age Group")
plt.ylabel("Hours")
plt.show()

sns.scatterplot(x='Avg_Daily_Usage_Hours', y='Sleep_Hours_Per_Night', data=df)
plt.title('Average Daily Usage Hours vs. Sleep Hours Per Night')
plt.xlabel('Average Daily Usage Hours')
plt.ylabel('Sleep Hours Per Night')
plt.show()

sns.scatterplot(x='Addicted_Score', y='Mental_Health_Score', data=df)
plt.title('Social Media Addiction Score vs. Mental Health Score')
plt.xlabel('Addiction Score')
plt.ylabel('Mental Health Score')
plt.show()

sns.scatterplot(x='Addicted_Score', y='Conflicts_Over_Social_Media', data=df)
plt.title('Social Media Addiction Score vs. Conflicts Over Social Media')
plt.xlabel('Addiction Score')
plt.ylabel('Conflicts Over Social Media')
plt.show()

# Pie Chart → Risk Level Distribution
df['Risk_Level'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Distribution of Risk Levels")
plt.show()

# Heatmap → Correlation Between Usage, Sleep, Mental Health and Addiction
sns.heatmap(df[['Avg_Daily_Usage_Hours','Sleep_Hours_Per_Night','Mental_Health_Score', 'Addicted_Score']].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

df.groupby("Academic_Level")['Avg_Daily_Usage_Hours'].mean().plot(kind='line', marker='o')
plt.title("Average Usage by Education Level")
plt.ylabel("Hours")
plt.show()

"""---


**Final Summary**


---

**The project analyzed student social media usage to combat addiction with data-driven insights.**

**Data cleaning involved checking for null values and duplicates, ensuring the dataset was ready for analysis.**

**Exploratory data analysis (EDA) revealed a negative correlation between average daily social media usage and hours of sleep per night**.

**Students were classified into low, medium, and high-risk categories for social media addiction based on their daily usage hours.**

**The project developed and applied a function to suggest personalized digital detox strategies for each risk level.**

**Visualizations, such as a pie chart, demonstrated the distribution of students across the different addiction risk levels.**

**A heatmap showed strong correlations between key variables like daily usage, sleep, and mental health scores.**

**The analysis indicated that younger students (ages 11-15) tend to have higher average daily usage hours compared to older age groups.**

**The strong negative correlations between social media engagement (usage and addiction) and both sleep and mental health suggest a significant public health concern for students.**

**The strong positive correlation between conflicts over social media and addiction scores indicates that addressing conflict resolution related to social media use could be a strategy in managing addiction.**
"""